### ISSUE TITLE
Add names to motors in motor class

### ISSUE THREAD

**Issue by pknessness** [Triton-Robotics/TR-mbed#13]
Assigning names to motors in the motor class will benefit debugging, so that we can be told "Left Pitch is overheating" instead of "[0][1][2] is overheating"

**Comment by GioByte10** [comment]
https://github.com/Triton-Robotics/TR-mbed/commit/e1ad69e99bc307ef2232ce91a121cec9e367e520

**Comment by GioByte10** [comment]
https://github.com/Triton-Robotics/TR-mbed/commit/e1ad69e99bc307ef2232ce91a121cec9e367e520

**Comment by GioByte10** [comment]
https://github.com/Triton-Robotics/TR-mbed/commit/c50003c65c17d0e10645fbafc240c94dce14ab8a

**Comment by GioByte10** [comment]
https://github.com/Triton-Robotics/TR-mbed/commit/c50003c65c17d0e10645fbafc240c94dce14ab8a
