### ISSUE TITLE
Is motor connected

### ISSUE THREAD

**Issue by pknessness** [Triton-Robotics/TR-mbed#15]
Have a very simple function/variable that is a reflection of if a motor is online (has it been giving us feedback) or not.

**Comment by GioByte10** [comment]
```C++
if(motorsExist[bus][r][c]) {
    if (us_ticker_read() / 1000 - lastCalled[bus][r][c] > TIMEOUT_MS) {
        if(debug) {
            printf("Motor %d on bus: %d lost connection\n", c + 4 * r + 1, bus + 1);
            printf("Motor[%d][%d][%d]\n", bus, r, c);
        }
        return false;
    }
}
```

**Comment by pknessness** [comment]
yeah ok thats what it was, i remmeber that you had done something similar but i realized during comp it would be more useful to have it motor specific so i can be like oh `if(pitch.isConnected)` or smth

**Comment by GioByte10** [comment]
https://github.com/Triton-Robotics/TR-mbed/commit/75d873e79ab2e41fc0a973d05f26d90ec1a50106

**Comment by GioByte10** [comment]
https://github.com/Triton-Robotics/TR-mbed/commit/75d873e79ab2e41fc0a973d05f26d90ec1a50106
