### ISSUE TITLE
Add constants for motor gearboxes in main code

### ISSUE THREAD

**Issue by pknessness** [Triton-Robotics/TR-mbed#22]
They're really wierd constants so we should add them either in motor class or in main

There's a fraction for M3508 but it basically equates to 19.2___
Both M3508 and M2006 gearbox constants can be found on datasheet, pinned in embed chat.

**Comment by GioByte10** [comment]
https://github.com/Triton-Robotics/TR-mbed/commit/4a1b9eeff5fdd0c51c770b8e31b6f22de655af5f

**Comment by GioByte10** [comment]
https://github.com/Triton-Robotics/TR-mbed/commit/4a1b9eeff5fdd0c51c770b8e31b6f22de655af5f

**Comment by GioByte10** [comment]
https://github.com/Triton-Robotics/TR-mbed/commit/4a1b9eeff5fdd0c51c770b8e31b6f22de655af5f
